//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_Gabdrakhmanov.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leaderboard
    {
        public int Id { get; set; }
        public Nullable<int> TournamentId { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> TotalWins { get; set; }
        public Nullable<int> TotalLoses { get; set; }
        public Nullable<int> Place { get; set; }
    
        public virtual Tournaments Tournaments { get; set; }
    }
}
