//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_Gabdrakhmanov.Components
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TournamentDB_422_GabdraxmanovEntities : DbContext
    {
        public TournamentDB_422_GabdraxmanovEntities()
            : base("name=TournamentDB_422_GabdraxmanovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccesLevel> AccesLevel { get; set; }
        public virtual DbSet<Format> Format { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<Leaderboard> Leaderboard { get; set; }
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<Organizators> Organizators { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Stats> Stats { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<TournamentHistory> TournamentHistory { get; set; }
        public virtual DbSet<TournamentParticipants> TournamentParticipants { get; set; }
        public virtual DbSet<Tournaments> Tournaments { get; set; }
        public virtual DbSet<TournamentTeam> TournamentTeam { get; set; }
        public virtual DbSet<Viewers> Viewers { get; set; }
    }
}
