//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_Gabdrakhmanov.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.TournamentParticipants = new HashSet<TournamentParticipants>();
            this.TournamentParticipants1 = new HashSet<TournamentParticipants>();
            this.Stats = new HashSet<Stats>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NIckaname { get; set; }
        public string Email { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<int> TotalMatches { get; set; }
        public Nullable<int> TotalWins { get; set; }
        public Nullable<int> TotalLoses { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> TeamId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentParticipants> TournamentParticipants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentParticipants> TournamentParticipants1 { get; set; }
        public virtual Role Role1 { get; set; }
        public virtual Team Team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stats> Stats { get; set; }
    }
}
