//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_Gabdrakhmanov.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stats
    {
        public int Id { get; set; }
        public Nullable<int> TournamentId { get; set; }
        public Nullable<int> TotalMatches { get; set; }
        public Nullable<int> TournamentsWinnerId { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> MVPId { get; set; }
    
        public virtual Organizators Organizators { get; set; }
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
    }
}
