//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_Gabdrakhmanov.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournaments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournaments()
        {
            this.Leaderboard = new HashSet<Leaderboard>();
            this.Matches = new HashSet<Matches>();
            this.TournamentHistory = new HashSet<TournamentHistory>();
            this.TournamentParticipants = new HashSet<TournamentParticipants>();
            this.TournamentParticipants1 = new HashSet<TournamentParticipants>();
            this.TournamentTeam = new HashSet<TournamentTeam>();
            this.TournamentTeam1 = new HashSet<TournamentTeam>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> GameId { get; set; }
        public Nullable<int> FormatId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> PrizeFund { get; set; }
        public Nullable<int> AmountParticipants { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Format Format { get; set; }
        public virtual Game Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leaderboard> Leaderboard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matches> Matches { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentHistory> TournamentHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentParticipants> TournamentParticipants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentParticipants> TournamentParticipants1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentTeam> TournamentTeam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentTeam> TournamentTeam1 { get; set; }
    }
}
