//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_Gabdrakhmanov.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentTeam
    {
        public int Id { get; set; }
        public Nullable<int> TournamentId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual Tournaments Tournaments { get; set; }
        public virtual Tournaments Tournaments1 { get; set; }
    }
}
